pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/asejour/genspark-sre-training/']]])
            }
        }
        
        stage('Launch init terraform') {
            steps{
                sh label: "", script:"terraform init"
            }
            
        }
        
        stage('test') {
            
            steps{
                
                echo "Ok continue---Emppty"
            }
            
        }
        
        stage('Launch apply terraform') {
            steps{
                sh label: "", script:"terraform apply --auto-approve"
            }
            
        }
        stage('Kubernetes Deploy'){
            
            steps{
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'k8-konfig', namespace: '', serverUrl: '') {
                sh "kubectl apply -f deployment.yaml"
                }
            }
        }
    }
}
